# GitHub Label Taxonomy Configuration
# Use with: https://github.com/marketplace/actions/github-labeler

# Component Labels
- name: "component: backend"
  color: "0052CC"
  description: "Backend-related changes"

- name: "component: frontend"
  color: "0E8A16"
  description: "Frontend UI/UX changes"

- name: "component: database"
  color: "006B75"
  description: "Database schema or query changes"

- name: "component: api"
  color: "1D76DB"
  description: "API endpoint changes"

# Priority Labels
- name: "priority: critical"
  color: "D73A4A"
  description: "Production-blocking issue"

- name: "priority: high"
  color: "FC8100"
  description: "High priority, address soon"

- name: "priority: medium"
  color: "FBCA04"
  description: "Medium priority"

- name: "priority: low"
  color: "D4C5F9"
  description: "Low priority, nice to have"

# Effort Labels
- name: "effort: small"
  color: "C2E0C6"
  description: "< 1 day of work"

- name: "effort: medium"
  color: "FEF2C0"
  description: "1-3 days of work"

- name: "effort: large"
  color: "F9D0C4"
  description: "> 3 days of work"

# Status Labels
- name: "status: needs-investigation"
  color: "E99695"
  description: "Requires research or investigation"

- name: "status: blocked"
  color: "D93F0B"
  description: "Blocked by external dependency"

- name: "status: in-progress"
  color: "2E7EEF"
  description: "Actively being worked on"

- name: "status: ready-review"
  color: "0E8A16"
  description: "Ready for code review"

# Type Labels
- name: "type: bug"
  color: "D73A4A"
  description: "Something isn't working"

- name: "type: feature"
  color: "A2EEEF"
  description: "New feature or request"

- name: "type: enhancement"
  color: "84B6EB"
  description: "Improvement to existing feature"

- name: "type: documentation"
  color: "0075CA"
  description: "Documentation improvements"

- name: "type: test"
  color: "BFDADC"
  description: "Testing improvements"

- name: "type: refactor"
  color: "D4C5F9"
  description: "Code refactoring"

- name: "type: performance"
  color: "FCD900"
  description: "Performance improvements"

- name: "type: security"
  color: "D73A4A"
  description: "Security vulnerability or improvement"
